version: "3.9"
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.dev.yaml:/etc/livekit.yaml
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
